### PR TITLE
Clear outputs in Model Card Generator example notebook

### PR DESCRIPTION
**Pull request by codesue**
Clears outputs in Model Card Generator example notebook for better readibility and easier reviews.

Tested the changes by running the notebook end to end in Colab.

### CODE REVIEW

**Review by hanneshapke — APPROVED** [review]

**Comment by codesue** [comment]
@hanneshapke Would you please merge this? I don't have write permissions for this repo and `/merge` isn't working for me. 🙏

**Comment by codesue** [comment]
Thank you!!

**Pull request merged**
