### PR TITLE
Update sklearn_predict_extractor.py

### PR DESCRIPTION
**Pull request by 1025KB**
Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by 1025KB** [comment]
Some context 

https://github.com/tensorflow/tfx/commit/2e11b28da00950ae4eaeef7caa1205cb25cbdb61

**Review by rcrowe-google — APPROVED** [review]
Thanks Jiayi!

**Comment by TheMichaelHu** [comment]
There appears to be a conflict between python formatters being used.

/lgtm

**Review by TheMichaelHu — APPROVED** [review]

**Comment by casassg** [comment]
Seems the CI job is failing due to pickling issues - https://github.com/tensorflow/tfx-addons/runs/5340812545?check_suite_focus=true

**Comment by casassg** [comment]
> I think it needs TFMA head / next release to work

You can modify requirements.txt to point to TFMA HEAD so we can make sure its green before merging.

**Comment by casassg** [comment]
yup. we can update once tfx is released to make sure. Meanwhile may be good to fix the linter issues (I can do it otherwise)

**Comment by 1025KB** [comment]
> yup. we can update once tfx is released to make sure. Meanwhile may be good to fix the linter issues (I can do it otherwise)

Curious, is there a quick cmd to fix lint? seems the git lint is different from my internal env :(

**Comment by casassg** [comment]
you can manually run pre-commit based on https://github.com/tensorflow/tfx-addons/blob/main/CONTRIBUTING.md#python-coding-style

**Comment by casassg** [comment]
Closing this as we archived the example

**Pull request closed without merging**
