### PR TITLE
Rename predictions_to_biquery to predictions_to_bigquery.

### LINKED ISSUE #213: Rename predictions_to_biquery to predictions_to_bigquery
## Expected Behavior
Component directory should be `tfx_addons/predictions_to_bigquery`

## Actual Behavior

Component directory is `tfx_addons/predictions_to_biquery`

## Steps to Reproduce the Problem

N/A

## Specifications

N/A

### PR DESCRIPTION
**Pull request by cfezequiel**
Fixes #213 .

- [ X ] Tests pass

### CODE REVIEW

**Review by hanneshapke — APPROVED** [review]

**Review by rcrowe-google — APPROVED** [review]
/lgtm

**Pull request merged**
