### PR TITLE
Add tfx 1.12 support

### PR DESCRIPTION
**Pull request by casassg**
PR just bumps upper limit.

### CODE REVIEW

**Review by hanneshapke — APPROVED** [review]

**Comment by hanneshapke** [comment]
@casassg Should we tie this change to a new tfxa version?

**Comment by casassg** [comment]
Yes, do you want to do a release? Else I can

**Comment by hanneshapke** [comment]
Happy to cut the release later today.

**Comment by casassg** [comment]
There's a timeout for some of pip resolvers again... sigh

**Comment by casassg** [comment]
Bumping up min version supported as otherwise it's a shitshow to maintain. Upgraded to tfx~=1.6

**Comment by casassg** [comment]
Unfortunately, we need to either drop support for feast, not add support for tfx 1.12 or drop support for py 3.7.

Current resolver error is caused by https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L100 which avoid protobuf 3.20 in tensorflow 2.11. This conflicts with latest py3.7 feast dependency for protobuf which is >3.20. Hence it makes resolver not find an option as it's non-resolvable.

@hanneshapke lmk wdyt on dropping 3.7

**Comment by hanneshapke** [comment]
@casassg Thank you for looking into this. TFX still supports 3.7. It would be a bummer to diverge from the requirements between tfx and tfxa, but understandable. @rcrowe-google do you know when tfx will drop the 3.7 support?

**Comment by casassg** [comment]
tests are broken on 3.8, still need to fix

**Comment by casassg** [comment]
Abandoning this in favour of #203 . Plan is release 0.5.0 with that change and then drop py 3.7 on 0.6 shortly after (while adding support for latest tfx)

**Pull request closed without merging**
