### PR TITLE
Restructure libraries folder + MLMD Client first commit

### PR DESCRIPTION
**Pull request by casassg**
`project/libraries` moves to `tfx_addons` folder for easier distribution of library with single package. 

In addition, I added pre-commit checks to run pylint, yapf and isort for the new library. Excluded projects folders to allow individual teams to set up their own CI there.

Also adds GitHub actions to run pre-commit checks and pytest for all files.

Test run of GitHub CI: https://github.com/casassg/tfx-addons/pull/1/checks

Discussion for library structure can be found here: https://groups.google.com/a/tensorflow.org/g/tfx-addons-core/c/FVstcFUAgb4

### CODE REVIEW

**Comment by rcrowe-google** [comment]
It's titled "first commit", which makes me think that you're planning on more?

**Comment by casassg** [comment]
For MLMD Client yes. The idea is to add a simple client class for now and build upon it until we are ready to release it. Since we have several folks on this project, this is just a small simple bootstrapping for the client

**Comment by rcrowe-google** [comment]
Go ahead and merge when you're ready.  I'm waiting for your new folder hierarchy to create project folders.

**Comment by casassg** [comment]
I cant merge since Im creating files in folders I have no permissions to write under

**Pull request merged**
