### PR TITLE
Update README.md to reflect membership changes

### PR DESCRIPTION
**Pull request by sngahane**
Dropping off the effort, thanks and bye folks!

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Review by rcrowe-google — APPROVED** [review]
Sorry to see you go, are you leaving Spotify?

**Comment by sngahane** [comment]
> Sorry to see you go, are you leaving Spotify?

I'm staying at Spotify @rcrowe-google but switching to a different focus area thus won't work closely with TFX/Kubeflow anymore ☺️

**Comment by rcrowe-google** [comment]
@sngahane -  Is there any chance that you can submit a contributor agreement? Otherwise I will have to close this PR and do the changes in a new PR.

**Comment by sngahane** [comment]
I've done it after seeing the failed check, would you mind rescanning this PR so that the changes are taken into account @rcrowe-google ?

**Pull request merged**
