### PR TITLE
Update examples for feature selection component

### PR DESCRIPTION
**Pull request by deutranium**
Updated examples for feature selection component, including spliiting the common file and updated the module file structure

### CODE REVIEW

**Review by rcrowe-google — APPROVED** [review]
Thanks!

**Comment by rcrowe-google** [comment]
Could you fix the conflicts?

**Review by FatimahAdwan — APPROVED** [review]

**Review by Nirzu97 — APPROVED** [review]

**Review by Nirzu97 — APPROVED** [review]

**Review by pratishtha-abrol — APPROVED** [review]

**Review by rcrowe-google — APPROVED** [review]
Thanks!

**Comment by rcrowe-google** [comment]
@deutranium @Nirzu97 @pratishtha-abrol @FatimahAdwan 

The auto-merge needs a comment from an owner (one of you) with /merge on a line by itself

**Comment by deutranium** [comment]
Thanks!

Oh, I think it needs a /merge by one of the other codeowners
Cc @FatimahAdwan @pratishtha-abrol @Nirzu97

**Comment by FatimahAdwan** [comment]
Hi, am finding it a little bit difficult to get to approve this ):

> Thanks!
> 
> Oh, I think it needs a /merge by one of the other codeowners Cc @FatimahAdwan @pratishtha-abrol @Nirzu97
okay let me check that

**Comment by FatimahAdwan** [comment]
> Hi, am finding it a little bit difficult to get to approve this ):
> 
> > Thanks!
> > Oh, I think it needs a /merge by one of the other codeowners Cc @FatimahAdwan @pratishtha-abrol @Nirzu97
> > okay let me check that

i think is done now, merged or so :)

**Comment by casassg** [comment]
yup @FatimahAdwan  you copying the comment from @deutranium was enough :P as it container /merge in it

**Comment by casassg** [comment]
Btw, can we remove stdout from notebooks? It adds a lot of content in the notebook which is not always easy to read. (just press Clear output before saving it)

**Comment by casassg** [comment]
(also the assumption is correct the bot ignores author /merge request as a way to increase consensus on merging things)

**Pull request merged**
