### PR TITLE
Model Load Test TFX Pipeline Component (reopened)

### PR DESCRIPTION
**Pull request by michalbrys**

### CODE REVIEW

**Comment by michalbrys** [comment]
Reopened pull requests after it was accidentally closed.
For the comments, see the old PR: https://github.com/tensorflow/tfx-addons/pull/26
CC: @hanneshapke

**Comment by michalbrys** [comment]
A high-level next steps proposal to structure the future work:
* define and write the component spec (inputs, outputs, execution parameters, see the proposal and [comments](https://github.com/tensorflow/tfx-addons/pull/26) )
* build the part for creating a TensorFlowServing endpoint (proposal: based on `InfraValidator TFX component` https://github.com/tensorflow/tfx/tree/master/tfx/components/infra_validator)
* build the part for creating prediction requests from imported TFExamples, see `InfraValidator TFX component` )
* build the part for the load test (initial proposal: start with GRPC endpoint, use external Docker image like ghz https://github.com/bojand/ghz, the image may be replaced by the user)

**Comment by rcrowe-google** [comment]
(Copying [this comment](https://github.com/tensorflow/tfx-addons/pull/26#discussion_r657617114) from @chongkong into this thread for visibility)

Sorry for the late follow-up! (Robert reminded me back to this thread)

1. So I assume it is not squeezing the model but test the moderate situation.. Or maybe we can frame it more generally as "any setting is okay; you can configure your model server and testing client setting to your taste, and this component simply provides bridge to that".
2. Agreed that model server should be on the separate container, and actually I was mainly asking about whether the "client" should be on the separate container. If client also runs on the separate container we would have total 3 containers running: 1 for component run, 1 for client, 1 for model server. If client runs on the same container that component runs, we would have total 2 containers: 1 for component + client run, 1 for model server. Unfortunately both options have a challenge which is...
3. (cont.) In either case, it is non-trivial how to bring load test binary (vegeta or ghz) to the container.
    1.  Case 1 (same container for client): Currently we uses `tensorflow/tfx` image for component container. Each component runs with the same image but with the different argument, so that entrypoint decides which component this container would run. If we use this same container as a load test client, such binary should be pre-installed in the container image. But I doubt we will do that for the standard `tensorflow/tfx` image because we cannot manage all dependencies for 3party addons. Instead, we should bake a new image (such as `tfx-addons/loadtest`) that is based on `tensorflow/tfx`, but with vegeta or ghz installed. But TFX team will probably be unable to maintain such container image.
    2.  Case 2 (separate container for client): If there is a separate container image with vegeta/ghz installed, we can use that container image for the load testing client. This is more affordable than case 1 because user can provide external container image as a config, and TFX team doesn't manage any extra container images. It would be even great if vegeta/ghz provides their own container images that TFX can use right away, but I don't know if they have ones. If we go with this option, I would like to ask you about more integration story included in this design.

**Comment by rcrowe-google** [comment]
(Copying [this comment](https://github.com/tensorflow/tfx-addons/pull/26#discussion_r642176199) into this thread for visibility)

If you look at TFX component codes, each component has its `ComponentSpec` which defines its input/output Artifact types and execution properties. I think you should also define what input and output artifact types it would use for the review. For example, `Examples` artifact is used to construct requests, `Model` artifact is used to serve it, and output artifact is either new type `ModelLoadTestResult` (I'm bad at naming..😅) or reuse the existing `ModelInfraBlessing` but with more custom properties or output files (files are placed under artifact's URI). Alternatively you can choose not to use `Model` artifact but use the pushed model network endpoint from cloud to directly send requests for "battle test".

**Comment by rcrowe-google** [comment]
(Copying [this comment](https://github.com/tensorflow/tfx-addons/pull/26#discussion_r642178270) from @chongkong into this thread for visibility)

Can you elaborate on what you mean to "extend" an InfraValidator? Do you want to inherit from its Executor implementation?

FYI we internally decided not to use InfraValidator directly as a load testing component due to the following reasons:
- InfraValidator is a canary component to mechanically check the model. It's purpose is to guarantee validity of the model, not model performance.
- Load testing should be done that is close as much as the real serving environment, while infra validator isn't designed so. Maybe load test is better done against the model that is pushed to the real world, but before it is publicly available.

**Comment by rcrowe-google** [comment]
(Copying [this comment](https://github.com/tensorflow/tfx-addons/pull/26#discussion_r642178874) from @chongkong into this thread for visibility)

It sounds like load testing component is a sub-component of the infra validator component. Since there is no sub-component (so that lifespan of the parent component encloses that of the child), would you elaborate on your intention?

**Comment by rcrowe-google** [comment]
(Copying [this comment](https://github.com/tensorflow/tfx-addons/pull/26#discussion_r642187719) from @chongkong into this thread for visibility)

FYI, ExampleGen's output is `Examples` artifact which typically contains `tf.Example` records. For serving requests we need to convert `tf.Example` to a [`PredictRequest`](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/predict.proto) (or ClassificationRequest or RegressionRequest, but those are rarely used these days) and optionally convert them to json for http request.

Converting `tf.Example` to `PredictRequest` is actually very tricky part because PredictRequest is about how model consumes the example, and it can be literally anything depending on the training code. Currently InfraValidator have a limited support on this auto conversion: it only supports Predict signature that takes serialized tf.Example. In other words, model should include a layer to deserialize it and feed it to the rest of the layers.

You can follow the InfraValidator behavior, or you can directly feed PredictRequest proto or json files using Importer node with custom artifact type.

**Comment by rcrowe-google** [comment]
(Copying [this comment](https://github.com/tensorflow/tfx-addons/pull/26#discussion_r657661447) from @chongkong into this thread for visibility)

Let's define what `ModelLoadTestResult` artifact is. Typically artifact have a directory with certain structure (for example fixed filename), and artifact properties (map of str to {number|str|ProtoStruct} values).

My recommendation is to put load test result into a single JSON field artifact property, and leave the directory (artifact.uri) empty unless you have any file-type artifacts:

```python
# I chose the different name here...
class ModelPerformanceMetric(Artifact):
  TYPE_NAME = "ModelPerformanceMetric"
  PROPERTIES = {
    "perf_metric": Property(type=PropertyType.JSON),
    "blessed": Property(type=PropertyType.INT, optional=True)
  }
```

Where perf_metric corresponds to a JSON something like..

```json
{
  "settings": {
    "machine_type": "n1-standard-16",
    "rps": 100
  },
  "result": {
    "inference_time_ms": {
      "average": 14,
      "p50": 16,
      "p75": 22,
      "p90": 29,
      "p99": 44
    }
  }
}
```

**Comment by rcrowe-google** [comment]
(Copying [this comment](https://github.com/tensorflow/tfx-addons/pull/26#discussion_r657662476) from @chongkong into this thread for visibility)

I just got confused on what's the difference between performance test and load testing, and read https://stackify.com/load-testing-vs-performance-testing-vs-stress-testing/. Can we say that our desired goal is "load testing" not "performance testing"? (because it feels like inference time distribution belong to performance test scope, and thought maybe this component is a PerformanceEvaluator?)

**Pull request merged**
