### PR TITLE
Prediction to bigquery component - initial code

### PR DESCRIPTION
**Pull request by hanneshapke**
Related to issue https://github.com/tensorflow/tfx-addons/issues/78

This is the OSS version of Digit's predictions to bigquery component.

What's missing and not part of this PR?
* dynamic BQ schema read from `prediction_log`
* tests covering the dynamic BQ schema

The component used by Digits' TFX pipelines.

### CODE REVIEW

**Review by michaelwsherman — APPROVED** [review]

**Comment by michaelwsherman** [comment]
LGTM

**Comment by casassg** [comment]
@hanneshapke seems the linter is failing mind fixing it up? Else new PRs may be blocked from merging https://github.com/tensorflow/tfx-addons/actions/runs/4099019498/jobs/7068535397

**Comment by casassg** [comment]
(also let's try to stick to using the automerge bot as bot ensures all tests/linters pass before merging avoiding issues like this)

**Comment by hanneshapke** [comment]
@casassg Sorry, I forgot to leave a comment about it. @michaelwsherman wanted to take over the project urgently. The component is missing the last piece (dyn schema) and it is therefore not functional. We shared it via the project, because @michaelwsherman can't fork from my dev branch.

**Comment by casassg** [comment]
@hanneshapke or @michaelwsherman mind adding lint ignore to all files until those get fixed? Want to avoid having to deal w issues on new PRs ideally

**Comment by michaelwsherman** [comment]
Echoing @hanneshapke, Google is going to finish up getting this merged in properly and adding some tests. But it may be a week or two before that's all done.

@casassg -- sorry about the rough edges here, but there was some challenges figuring out a way for Google to work on Hannes code, and getting the working code into the tfx-addons repo was the best way we could figure out how to collaborate. Would it be safer to move this "working" code into a subfolder of the root rather a subfolder of `tfx_addons` where it's in the package?

**Comment by hanneshapke** [comment]
Happy to craete a fix for it in a moment

**Comment by michaelwsherman** [comment]
@cfezequiel to add linter annotations if Hannes doesn't get to it first. Sorry folks, on the move today and hard for me to just bang this out myself.

**Comment by casassg** [comment]
Got it fixed up, should be fine now. Let's try to remove the linter skip annotations

**Pull request merged**
