### PR TITLE
Archive penguins_sklearn example

### PR DESCRIPTION
**Pull request by rcrowe-google**
Archiving the penguins sklearn example since it has no current owner.

### CODE REVIEW

**Comment by casassg** [comment]
This still triggers CI as the test files are still there (even if commented, for some reason pytest files if it doesnt find a test). We may need to modify CI to not fail if no test found?

**Comment by rcrowe-google** [comment]
> 

Or maybe I can just write a null test?

**Comment by rcrowe-google** [comment]
> > This still triggers CI as the test files are still there (even if commented, for some reason pytest files if it doesnt find a test). We may need to modify CI to not fail if no test found?
> 
> Or maybe I can just write a null test?

Passing CI now.

**Review by casassg — APPROVED** [review]
/lgtm for now we may think if we just want to delete the files later as an alternative

**Comment by rcrowe-google** [comment]
> /lgtm for now we may think if we just want to delete the files later as an alternative (aka delete everything except readme file). Files can be recovered from git either way

Good idea, I like that better.  Initially I thought that commenting out would be simpler than it turned out to be.

**Pull request merged**
