### PR TITLE
Support remote storage in modelcardgenerator

### LINKED ISSUE #261: Cannot write model card when pipeline root is in GCS
## Expected Behavior

When setting pipeline_root to the Google Cloud Storage path, I couldn't write the model card properly.

## Actual Behavior

Model Card Toolkit cannot write model card files to remote storage.

Code Flow: 

* ModelCardToolkit.export_format: https://github.com/tensorflow/model-card-toolkit/blob/74d7e6d8d3163b830711b226491ccd976a2d7018/model_card_toolkit/core.py#L363-L419
* ModelCard.render: https://github.com/tensorflow/model-card-toolkit/blob/74d7e6d8d3163b830711b226491ccd976a2d7018/model_card_toolkit/model_card.py#L548-L580
* template_utils.render: https://github.com/tensorflow/model-card-toolkit/blob/74d7e6d8d3163b830711b226491ccd976a2d7018/model_card_toolkit/utils/template_utils.py#L43-L72
* io_utils.write_file: https://github.com/tensorflow/model-card-toolkit/blob/74d7e6d8d3163b830711b226491ccd976a2d7018/model_card_toolkit/utils/io_utils.py#L29-L44

  ```py
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, mode) as f:
      f.write(content)
  ```

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version: model-card-toolkit==2.0.0, tfx-addons 0.6.0
- Platform: vertex ai

### PR DESCRIPTION
**Pull request by jeongukjae**
Fixes #261

I updated the MCT generator to create a temp dir for all cases since I don't think that's a big operation.

- [x] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Review by codesue — APPROVED** [review]

**Comment by codesue** [comment]
Hi @rcrowe-google or @casassg, would you please take a look at this PR since Hannes is currently unavailable. 🙏

**Review by rcrowe-google — APPROVED** [review]
I'm not listed as an owner so I don't think I can actually approve this:

>Missing approvals for PR. Potential owners: @codesue and @hanneshapke

**Comment by codesue** [comment]
Thank you, Robert! My apologies; I think I blanked and forgot about the bot. I'll be more mindful about this next time. 😅

**Comment by casassg** [comment]
btw just a heads up. The bot adds and removes labels in the PR as needed. if it has lgtm, then only is missing / merge command

**Pull request merged**
