### PR TITLE
predictions-to-bigquery: Update FilterPredictionToDictFn.

### LINKED ISSUE #218: Incomplete implementation of FilterPredictionToDictFn in predictions-to-bigquery component.
## Expected Behavior
In executor.py, the FilterPredictionToDictFn should process an element (PredictionLog) from an Apache Beam PCollection and converts it into a dict with input features and prediction label + score.

## Actual Behavior
Parsing of the input features from the element is incomplete and was left as a TODO. 

## Steps to Reproduce the Problem

N/A

## Specifications

- Version: Python 3.9

### PR DESCRIPTION
**Pull request by cfezequiel**
Updates process method to parse the element (PredictionLog) and extract the input tf.Example as dict and combine it with the prediction results.

Fixes #218 

> It's a good idea to open an issue first for discussion.

- [ X ] Tests pass
- [ X ] Appropriate changes to README are included in PR

### CODE REVIEW

**Review by hanneshapke — APPROVED** [review]

**Comment by cfezequiel** [comment]
@hanneshapke thanks for the approval.
@rcrowe-google @theadactyl I believe one your approvals is needed as well to merge the PR. Please have a look when you have time. I have a follow on PR that I'm planning to submit after this one.

**Comment by hanneshapke** [comment]
@cfezequiel Do you mind updating the `CODEOWNERS` file?
There is a typo `/tfx_addons/predictions_to_biquery`, otherwise I could sign off on it.
No need for Thea's approval

**Review by rcrowe-google — APPROVED** [review]
Looks good, thanks especially for adding the tests!

**Comment by hanneshapke** [comment]
@cfezequiel @rcrowe-google Who is making the `CODEOWNER` change?

**Pull request merged**
